name: Epic
description: Collection of agile stories
title: "[Epic]: "
labels: ["Epic"]
assignees:
  - 
body:
  - type: textarea
    id: description
    attributes:
      label: Epic description
      placeholder:
    validations:
      required: false
  - type: textarea
    id: epic-stories
    attributes:
      label: Stories
      description: Add a list of stories
      value: "1. [ ] "
    validations:
      required: false
